# TP02

Exercice 1 : Exploration de env FrozenLake

In [ ]:
import numpy as np
import gym
import plotly.graph_objects as go

In [ ]:
env = gym.make("FrozenLake-v1", is_slippery=True)
print("Action Space:", env.action_space)
print("Observation Space:", env.observation_space)

Action Space: Discrete(4)
Observation Space: Discrete(16)


Implémenintion de Q-Table et l'initialisation

In [ ]:
num_states = env.observation_space.n
num_actions = env.action_space.n
Q_table = np.zeros((num_states, num_actions))

# Hyperparameters
alpha = 0.1  # Learning rate
gamma = 0.99  # Discount factor
epsilon = 1.0  # Exploration-exploitation trade-off
epsilon_decay = 0.995
epsilon_min = 0.01
episodes = 5000


Q-Learning avec Mise à Jour

In [ ]:
rewards_per_episode = []

def train_q_learning():
    global epsilon
    for episode in range(episodes):
        state = env.reset()[0]  
        done = False
        total_reward = 0
        
        while not done:
            if np.random.uniform(0, 1) < epsilon:
                action = env.action_space.sample()  
            else:
                action = np.argmax(Q_table[state, :]) 
            
            new_state, reward, done, _, _ = env.step(action)
            
            Q_table[state, action] = (1 - alpha) * Q_table[state, action] + \
                                     alpha * (reward + gamma * np.max(Q_table[new_state, :]))
            
            total_reward += reward
            state = new_state
        
        epsilon = max(epsilon * epsilon_decay, epsilon_min)
        rewards_per_episode.append(total_reward)
    
    print("Training complete.")

train_q_learning()

Training complete.


In [ ]:
def plot_rewards():
    fig = go.Figure()
    fig.add_trace(go.Scatter(y=rewards_per_episode, mode='lines', name='Rewards per episode'))
    fig.update_layout(title='Q-Learning Training Progress',
                      xaxis_title='Episodes',
                      yaxis_title='Rewards',
                      template='plotly_dark',
                      width=1000, height=500)
    fig.show()

plot_rewards()



In [ ]:
def display_q_table():
    print("Final Q-Table:")
    print(Q_table)

display_q_table()

Final Q-Table:
[[0.51727859 0.49944632 0.44170332 0.41834975]
 [0.00756377 0.2150477  0.02833383 0.00376848]
 [0.26241133 0.01884829 0.12465992 0.05351152]
 [0.00310381 0.07845862 0.00132348 0.00690935]
 [0.54320607 0.30045876 0.35400205 0.37521884]
 [0.         0.         0.         0.        ]
 [0.15173149 0.05112918 0.21139079 0.07563838]
 [0.         0.         0.         0.        ]
 [0.28760786 0.45441268 0.36423388 0.56984187]
 [0.52797644 0.62603457 0.2603609  0.37949583]
 [0.62549171 0.40756046 0.3209012  0.27035366]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.48638058 0.39287989 0.74885072 0.47074341]
 [0.68567512 0.87682928 0.76578317 0.76724045]
 [0.         0.         0.         0.        ]]


<p align="center">EL HACHYMI Ahmed Yassine</p>
